### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gbbn** [IonAgorria/ProposalToOrder#1]
Does it work with 3.5.0 ?

**Comment by IonAgorria** [comment]
Yes, the company who solicited this was using 3.5.0 and said it was working
so far, If there is any problem feel free to notify me

2014-02-20 17:54 GMT+01:00 Guillaume notifications@github.com:

**Comment by gbbn** [comment]
Thank you
How does it work ? I try to install it  in Dolibarr 3.5.0 but I can't find it in modules to activate.

**Comment by IonAgorria** [comment]
Umm check that the module is named "proposaltoorder", all lowercase and see
if works

2014-02-21 18:45 GMT+01:00 Guillaume notifications@github.com:

**Comment by gbbn** [comment]
Ok I find it. I activate the module but I do not understand how it works :-(

**Comment by IonAgorria** [comment]
When you validate a Proposal, It will ask if you want to convert it to a
order

2014-02-21 23:13 GMT+01:00 Guillaume notifications@github.com:

**Comment by gbbn** [comment]
I must be stupid. It does not work. I wander if I install it correctly.
In which folder is suppose to be "convert.php" ? In htdocs ? And the others files ?
Thank you for your help.

**Comment by IonAgorria** [comment]
Everything you see in github must be put in the "proposaltoorder" folder
(all lowercase) and that folder must be in htdocs or custom folder

(remember that I'm human and there might be some bug, if you see one I will
try to fix it)

2014-02-22 8:55 GMT+01:00 Guillaume notifications@github.com:

**Comment by gbbn** [comment]
Ok, thank you.
When I validate a propale I got a new window with "PopupContent" then a page with error message (few seconds) then go back to propale page.
